### ISSUE TITLE
TypeError: Cannot read property 'fluid' of undefined

### ISSUE THREAD

**Issue by ghost** [akzhy/gatsby-starter-elemental#8]
I've searched everywhere for a solution but I can't seem to track down what is happening.

When using `gatsby develop` and viewing in the browser, I get this error:

`TypeError: Cannot read property 'fluid' of undefined`

All I've done was remove a couple things from `gatsby-config.js` and add my own images to the `static` folder.

If you can take a look at my repo I'd appreciate it. It's a great starter, just need to track this down.

[Build Blog](https://github.com/twhite96/build_blog)

**Comment by akzhy** [comment]
Hi @twhite96 , this is a weird problem. It is due to a `regex` issue. The blog posts are queried based on their absolute path, ie all markdown files that contain "blog" are queried. Now the issue (I believe) is that you have named your project `build_blog` which has the word "blog" in it so all files in your project folder are queried.

So what you can do is either rename your project to something that doesn't contain "blog" in it, or I can update your code so that it strictly checks for content inside the contents folder.

**Comment by ghost** [comment]
Thanks @akzhy that fixed it. However there's some jank when refreshing the page. I added a gatsby plugin to reduce the flashing when loading the page when coming from light mode to dark mode and vice versa. I'm still trying to track down the jank bug though.

**Comment by akzhy** [comment]
Hi, can you explain a bit more on what you mean by jank bug, also where does it occur ? @twhite96

**Comment by ghost** [comment]
@akzhy the page jumps when it is refreshed. I think it is an issue of me deleting the portfolio section. I can't take a look until probably tomorrow as I just moved and haven't setup everything yet. But if you clone my repo and load it you will get a sense of what I am talking about.

**Comment by akzhy** [comment]
@twhite96 Hi, can you take a look at https://elemental.netlify.com/ and check if the issue exists there ? I had made some updates to it, the latest fix might be what you are looking for.

**Comment by ghost** [comment]
@akzhy there's a flash but no jumpiness. I still haven't set up my personal Mac to pull the updated yet but when I do I'll check it out.
